### PR TITLE
Support both pre- and post- padding

### PR DESCRIPTION
**Pull request by alexeyr**

### CODE REVIEW

**Comment by Hironsan** [comment]
Please add some test cases. Thanks!

**Comment by alexeyr** [comment]
I was trying to figure out how to test Keras callbacks, but unsuccessfully so far :( My idea is to create a dummy `Model` which simply returns rows of `y_pred`.

**Comment by Hironsan** [comment]
You will be able to use mock:

* https://docs.python.org/3/library/unittest.mock.html

**Comment by alexeyr** [comment]
Added tests.

**Comment by alexeyr** [comment]
Not using mock, but I think it's better to verify that it works correctly in Keras' real context; if changes in Keras break it, we should know.

**Comment by alexeyr** [comment]
@Hironsan Do you need any further changes here?

**Comment by Hironsan** [comment]
Thanks!

**Pull request merged**
