### PR TITLE
Add performance metrics function - TP, FP, FN, TN

### PR DESCRIPTION
**Pull request by nipunsadvilkar**
Compute the performance metrics: TP, FP, FN, TN

### CODE REVIEW

**Comment by Hironsan** [comment]
Could you please write test code?

**Comment by nipunsadvilkar** [comment]
Woah..that was a very quick reply!😅

will push tests in a while

**Comment by nipunsadvilkar** [comment]
@Hironsan : Unable to push code

`fatal: unable to access 'https://github.com/chakki-works/seqeval/': The requested URL returned error: 403`

**Comment by Hironsan** [comment]
Thanks!

**Pull request merged**
